name: Compile C++ Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libcurl4-openssl-dev

    # Step 3: Compile the C++ file
    - name: Compile C++ Code
      run: g++ -o stx_gacor_final -pthread -std=c++17 stx_gacor_final.cpp -lcurl

    # Step 4: Verify compiled binary
    - name: Verify Output
      run: |
        if [ ! -f ./stx ]; then
          echo "Compilation failed: Binary not found!"
          exit 1
        fi
        echo "Compilation successful: Binary created."
